version: '2'
services:
  mysql_slave:
    image: mysql:5.7.21
    container_name: mysql_slave
    volumes:
      - mysql_slave:/var/lib/mysql
      - ./mysql_slave.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw123
    ports:
      - "3306:3306"

volumes:
  mysql_slave: