version: '2'
services:
  redis_master:
    image: redis:latest
    container_name: redis_master
    restart: always
    volumes:
      - redis_master:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf --maxmemory 200mb --requirepass redispw
    ports:
      - 6379:6379

volumes:
  redis_master: